language: node_js
sudo: false
node_js:
  - stable
script:
  - npm run ci
after_success:
  - mkdir coverage
  - npx nyc report --reporter=json > coverage/coverage.json
  - npx codecov
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
